install.packages("dplyr", repos="http://cran.us.r-project.org")
library(dplyr)
args = commandArgs(trailingOnly=TRUE)

sink(args[2])
data <- read.csv(args[1])
combined_data <- filter(data, type == "combined")
not_dropped <- filter(combined_data, dropped == "false")
quantile(not_dropped$latency, c(.25, .5, .75, .95, .99))
sink()
